### ISSUE TITLE
[Bug](context): cannot choose Plugin on 0.6.0

### ISSUE THREAD

**Issue by olandr** [cloudoperators/juno#992]
When running Greenhouse [0.6.0](https://github.com/orgs/cloudoperators/packages/container/juno-app-greenhouse/428626432?tag=0.6.0) locally I run into a problem where trying to select a Plugin turns the page blank and an error is thrown.

**Steps to Reproduce**

1. Setup Greenhouse locally: cd [greenhouse](https://github.com/cloudoperators/greenhouse) && make setup
1. Kubectl apply an arbitrary plugin e.g. cert-manager
1. Port-forward the dashboard and greenhouse
1. Navigate to the Dashboard > Plugins
1. Press to open the "Add Plugin" blade
1. Press e.g. cert-manager

**Expected Behavior**

I should get a config blade to configure cert-manager.

**Screenshots**

Error:
```
TypeError: this.getData is not a function. (In 'this.getData("inTable")', 'this.getData' is undefined)
```

<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/5628cd0e-3d47-46ad-b78f-4b32ea5ed579" />

**Environment**

- OS: macOS
- Browser: Safari
- Version: 18.5 (20621.2.5.11.8)

**Additional Context**

It worked fine in 0.5.7

**Comment by olandr** [comment]
<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/18acfae1-bc33-4801-bddf-24072cc06f20" />


<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/2afc73a3-bb24-4508-a02b-8d41ef326e1d" />

**Comment by olandr** [comment]
> If you are using the Greenhouse Image and not a local dev setup for the UI you should be save.

I do not understand what you mean here, the local environment setup will install the latest version.

**Comment by ArtieReus** [comment]
> <img alt="Image" width="1502" src="https://private-user-images.githubusercontent.com/41926603/450777053-18acfae1-bc33-4801-bddf-24072cc06f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg5NTk2NjQsIm5iZiI6MTc0ODk1OTM2NCwicGF0aCI6Ii80MTkyNjYwMy80NTA3NzcwNTMtMThhY2ZhZTEtYmMzMy00ODAxLWJkZGYtMjQwNzJjYzA2ZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjAzVDE0MDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWJjMGMyOGY2Y2NhMWQ5MjQ3YmVlMTE1OGU0Njc5NTllOWMzYzg5NDA5MzgyZDEyNjMzNjg4M2NkZWE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.px00IpkiGdLQgG_wHaimoOgS0tZqbTBtB5hftvaKUUg"> <img alt="Image" width="1510" src="https://private-user-images.githubusercontent.com/41926603/450777215-2afc73a3-bb24-4508-a02b-8d41ef326e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg5NTk2NjQsIm5iZiI6MTc0ODk1OTM2NCwicGF0aCI6Ii80MTkyNjYwMy80NTA3NzcyMTUtMmFmYzczYTMtYmIyNC00NTA4LWEwMmItOGQ0MWVmMzI2ZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjAzVDE0MDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzNmMDE1M2JlYTM0MjgxMmM3ZTRkNTczZmMxOTk5OGUzNGMxNjBkNzEyMTI3NGM3NDZlM2RlNDY5MWNhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pfnMR2yW58bpKMWp0Vr67kEfkG4OWcWA9i2iN5YKpoM">

Can you please display/open this section so I get more context. I can't reproduce it.

```js
TypeError: this.getData is not a function. (In 'this.getData("inTable")', 'this.getData' is undefined)
```

**Comment by ArtieReus** [comment]
Fixed with #997
